notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
 - CC=gcc

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - curl
   - zlib1g-dev
   - libncurses5-dev
   - libpstreams-dev
   - libcurl4-openssl-dev
   - liblzma-dev

install: true

language: perl

perl:
 - "5.22"

script:
 - ./setup.sh $HOME/VAGrENT-opt
